
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry terning2;

	private global::Gtk.Entry terning3;

	private global::Gtk.Entry terning4;

	private global::Gtk.Entry terning5;

	private global::Gtk.Entry terning1;

	private global::Gtk.Button nytSpil;

	private global::Gtk.CheckButton holdTerning3;

	private global::Gtk.CheckButton holdTerning4;

	private global::Gtk.CheckButton holdTerning5;

	private global::Gtk.CheckButton holdTerning1;

	private global::Gtk.CheckButton holdTerning2;

	private global::Gtk.Button kastTerninger;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Label Label1;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.VSeparator vseparator4;

	private global::Gtk.Button Ettere;

	private global::Gtk.Button Toere;

	private global::Gtk.Button Treere;

	private global::Gtk.Button Fiere;

	private global::Gtk.Button Femmere;

	private global::Gtk.Button Seksere;

	private global::Gtk.Entry pointEttere;

	private global::Gtk.Entry pointToere;

	private global::Gtk.Entry pointTreere;

	private global::Gtk.Entry pointfiere;

	private global::Gtk.Entry pointFemmere;

	private global::Gtk.Entry pointSeksere;

	private global::Gtk.Button seMuligheder;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.terning2 = new global::Gtk.Entry();
		this.terning2.CanFocus = true;
		this.terning2.Name = "terning2";
		this.terning2.IsEditable = true;
		this.terning2.WidthChars = 5;
		this.terning2.InvisibleChar = '●';
		this.fixed1.Add(this.terning2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.terning2]));
		w1.X = 500;
		w1.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.terning3 = new global::Gtk.Entry();
		this.terning3.CanFocus = true;
		this.terning3.Name = "terning3";
		this.terning3.IsEditable = true;
		this.terning3.WidthChars = 5;
		this.terning3.InvisibleChar = '●';
		this.fixed1.Add(this.terning3);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.terning3]));
		w2.X = 600;
		w2.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.terning4 = new global::Gtk.Entry();
		this.terning4.CanFocus = true;
		this.terning4.Name = "terning4";
		this.terning4.IsEditable = true;
		this.terning4.WidthChars = 5;
		this.terning4.InvisibleChar = '●';
		this.fixed1.Add(this.terning4);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.terning4]));
		w3.X = 700;
		w3.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.terning5 = new global::Gtk.Entry();
		this.terning5.CanFocus = true;
		this.terning5.Name = "terning5";
		this.terning5.IsEditable = true;
		this.terning5.WidthChars = 5;
		this.terning5.InvisibleChar = '●';
		this.fixed1.Add(this.terning5);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.terning5]));
		w4.X = 800;
		w4.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.terning1 = new global::Gtk.Entry();
		this.terning1.WidthRequest = 0;
		this.terning1.HeightRequest = 0;
		this.terning1.CanFocus = true;
		this.terning1.Name = "terning1";
		this.terning1.IsEditable = true;
		this.terning1.WidthChars = 5;
		this.terning1.InvisibleChar = '●';
		this.fixed1.Add(this.terning1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.terning1]));
		w5.X = 400;
		w5.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nytSpil = new global::Gtk.Button();
		this.nytSpil.WidthRequest = 100;
		this.nytSpil.HeightRequest = 50;
		this.nytSpil.CanFocus = true;
		this.nytSpil.Name = "nytSpil";
		this.nytSpil.UseUnderline = true;
		this.nytSpil.Label = global::Mono.Unix.Catalog.GetString("Start nyt spil");
		this.fixed1.Add(this.nytSpil);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.nytSpil]));
		w6.X = 14;
		w6.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.holdTerning3 = new global::Gtk.CheckButton();
		this.holdTerning3.CanFocus = true;
		this.holdTerning3.Name = "holdTerning3";
		this.holdTerning3.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.holdTerning3.DrawIndicator = true;
		this.holdTerning3.UseUnderline = true;
		this.fixed1.Add(this.holdTerning3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.holdTerning3]));
		w7.X = 600;
		w7.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.holdTerning4 = new global::Gtk.CheckButton();
		this.holdTerning4.CanFocus = true;
		this.holdTerning4.Name = "holdTerning4";
		this.holdTerning4.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.holdTerning4.DrawIndicator = true;
		this.holdTerning4.UseUnderline = true;
		this.fixed1.Add(this.holdTerning4);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.holdTerning4]));
		w8.X = 700;
		w8.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.holdTerning5 = new global::Gtk.CheckButton();
		this.holdTerning5.CanFocus = true;
		this.holdTerning5.Name = "holdTerning5";
		this.holdTerning5.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.holdTerning5.DrawIndicator = true;
		this.holdTerning5.UseUnderline = true;
		this.fixed1.Add(this.holdTerning5);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.holdTerning5]));
		w9.X = 800;
		w9.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.holdTerning1 = new global::Gtk.CheckButton();
		this.holdTerning1.CanFocus = true;
		this.holdTerning1.Name = "holdTerning1";
		this.holdTerning1.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.holdTerning1.DrawIndicator = true;
		this.holdTerning1.UseUnderline = true;
		this.fixed1.Add(this.holdTerning1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.holdTerning1]));
		w10.X = 400;
		w10.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.holdTerning2 = new global::Gtk.CheckButton();
		this.holdTerning2.CanFocus = true;
		this.holdTerning2.Name = "holdTerning2";
		this.holdTerning2.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.holdTerning2.DrawIndicator = true;
		this.holdTerning2.UseUnderline = true;
		this.fixed1.Add(this.holdTerning2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.holdTerning2]));
		w11.X = 500;
		w11.Y = 89;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.kastTerninger = new global::Gtk.Button();
		this.kastTerninger.HeightRequest = 40;
		this.kastTerninger.CanFocus = true;
		this.kastTerninger.Name = "kastTerninger";
		this.kastTerninger.UseUnderline = true;
		this.kastTerninger.Label = global::Mono.Unix.Catalog.GetString("Kast terninger");
		this.fixed1.Add(this.kastTerninger);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.kastTerninger]));
		w12.X = 869;
		w12.Y = 53;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.WidthRequest = 700;
		this.hseparator1.Name = "hseparator1";
		this.fixed1.Add(this.hseparator1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator1]));
		w13.X = 300;
		w13.Y = 30;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Label1 = new global::Gtk.Label();
		this.Label1.Name = "Label1";
		this.Label1.LabelProp = global::Mono.Unix.Catalog.GetString("Terninger");
		this.fixed1.Add(this.Label1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Label1]));
		w14.X = 325;
		w14.Y = 36;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.HeightRequest = 100;
		this.vseparator1.Name = "vseparator1";
		this.fixed1.Add(this.vseparator1);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vseparator1]));
		w15.X = 300;
		w15.Y = 32;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.vseparator4 = new global::Gtk.VSeparator();
		this.vseparator4.HeightRequest = 100;
		this.vseparator4.Name = "vseparator4";
		this.fixed1.Add(this.vseparator4);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vseparator4]));
		w16.X = 997;
		w16.Y = 32;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Ettere = new global::Gtk.Button();
		this.Ettere.CanFocus = true;
		this.Ettere.Name = "Ettere";
		this.Ettere.UseUnderline = true;
		this.Ettere.Label = global::Mono.Unix.Catalog.GetString("Ettere");
		this.fixed1.Add(this.Ettere);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Ettere]));
		w17.X = 23;
		w17.Y = 228;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Toere = new global::Gtk.Button();
		this.Toere.CanFocus = true;
		this.Toere.Name = "Toere";
		this.Toere.UseUnderline = true;
		this.Toere.Label = global::Mono.Unix.Catalog.GetString("Toere");
		this.fixed1.Add(this.Toere);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Toere]));
		w18.X = 20;
		w18.Y = 271;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Treere = new global::Gtk.Button();
		this.Treere.CanFocus = true;
		this.Treere.Name = "Treere";
		this.Treere.UseUnderline = true;
		this.Treere.Label = global::Mono.Unix.Catalog.GetString("Treere");
		this.fixed1.Add(this.Treere);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Treere]));
		w19.X = 20;
		w19.Y = 312;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Fiere = new global::Gtk.Button();
		this.Fiere.CanFocus = true;
		this.Fiere.Name = "Fiere";
		this.Fiere.UseUnderline = true;
		this.Fiere.Label = global::Mono.Unix.Catalog.GetString("Fiere");
		this.fixed1.Add(this.Fiere);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Fiere]));
		w20.X = 22;
		w20.Y = 352;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Femmere = new global::Gtk.Button();
		this.Femmere.CanFocus = true;
		this.Femmere.Name = "Femmere";
		this.Femmere.UseUnderline = true;
		this.Femmere.Label = global::Mono.Unix.Catalog.GetString("Femmere");
		this.fixed1.Add(this.Femmere);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Femmere]));
		w21.X = 24;
		w21.Y = 393;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Seksere = new global::Gtk.Button();
		this.Seksere.CanFocus = true;
		this.Seksere.Name = "Seksere";
		this.Seksere.UseUnderline = true;
		this.Seksere.Label = global::Mono.Unix.Catalog.GetString("Seksere");
		this.fixed1.Add(this.Seksere);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Seksere]));
		w22.X = 25;
		w22.Y = 435;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pointEttere = new global::Gtk.Entry();
		this.pointEttere.CanFocus = true;
		this.pointEttere.Name = "pointEttere";
		this.pointEttere.IsEditable = true;
		this.pointEttere.InvisibleChar = '●';
		this.fixed1.Add(this.pointEttere);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pointEttere]));
		w23.X = 75;
		w23.Y = 228;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pointToere = new global::Gtk.Entry();
		this.pointToere.CanFocus = true;
		this.pointToere.Name = "pointToere";
		this.pointToere.IsEditable = true;
		this.pointToere.InvisibleChar = '●';
		this.fixed1.Add(this.pointToere);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pointToere]));
		w24.X = 72;
		w24.Y = 272;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pointTreere = new global::Gtk.Entry();
		this.pointTreere.CanFocus = true;
		this.pointTreere.Name = "pointTreere";
		this.pointTreere.IsEditable = true;
		this.pointTreere.InvisibleChar = '●';
		this.fixed1.Add(this.pointTreere);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pointTreere]));
		w25.X = 79;
		w25.Y = 311;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pointfiere = new global::Gtk.Entry();
		this.pointfiere.CanFocus = true;
		this.pointfiere.Name = "pointfiere";
		this.pointfiere.IsEditable = true;
		this.pointfiere.InvisibleChar = '●';
		this.fixed1.Add(this.pointfiere);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pointfiere]));
		w26.X = 75;
		w26.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pointFemmere = new global::Gtk.Entry();
		this.pointFemmere.CanFocus = true;
		this.pointFemmere.Name = "pointFemmere";
		this.pointFemmere.IsEditable = true;
		this.pointFemmere.InvisibleChar = '●';
		this.fixed1.Add(this.pointFemmere);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pointFemmere]));
		w27.X = 96;
		w27.Y = 390;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pointSeksere = new global::Gtk.Entry();
		this.pointSeksere.CanFocus = true;
		this.pointSeksere.Name = "pointSeksere";
		this.pointSeksere.IsEditable = true;
		this.pointSeksere.InvisibleChar = '●';
		this.fixed1.Add(this.pointSeksere);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.pointSeksere]));
		w28.X = 93;
		w28.Y = 432;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.seMuligheder = new global::Gtk.Button();
		this.seMuligheder.CanFocus = true;
		this.seMuligheder.Name = "seMuligheder";
		this.seMuligheder.UseUnderline = true;
		this.seMuligheder.Label = global::Mono.Unix.Catalog.GetString("Se muligheder");
		this.fixed1.Add(this.seMuligheder);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.seMuligheder]));
		w29.X = 26;
		w29.Y = 160;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1101;
		this.DefaultHeight = 648;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.kastTerninger.Clicked += new global::System.EventHandler(this.OnKastTerningerClicked);
	}
}
